List<String> _englishVerse = [
  'For this is the reason\nthe gospel was preached even to\nthose who are now dead,\nso that they might be judged\naccording to men in regard to the body,\nbut live according to God\nin regard to the spirit.\n\n1 Peter 4:6',
  "Because of the LORD's great love\nwe are not consumed,\nfor his compassions never fail.\nThey are new every morning\ngreat is your faithfulness.\n\nLamentations 3:22-23",
  "Greater love has no one than this,\nthat he lay down his life for his friends.\n\nJohn 15:13",
  "Now unto him\nthat is able to do exceeding\nabundantly above all that we ask or think,\naccording to the power\nthat worketh in us\n\nEphesians 3:20",
  "Be strong and of a good courage,\nfear not, nor be afraid of them\nfor the LORD thy God,\nhe it is that doth go with thee\nhe will not fail thee,\nnor forsake thee.\n\nDeuteronomy 31:6",
  "The LORD is my light\nand my salvation\nwhom shall I fear?\nthe LORD is the strength of my life\nof whom shall I be afraid?\n\nPsalm 27:1",
  "There is no fear in love.\nBut perfect love drives out fear,\nbecause fear has to do with punishment.\nThe one who fears\nis not made perfect in love.\n\n1 John 4:18",
  "What, then, shall we say\nin response to this?\nIf God is for us,\nwho can be against us?\n\nRomans 8:31",
  "May the God of hope\nfill you with all joy and peace\nas you trust in him,\nso that you may overflow\nwith hope by\nthe power of the Holy Spirit.\n\nRomans 15:13",
  "Be of good courage,\nand he shall strengthen your heart,\nall ye that hope in the LORD.\n\nPsalm 31:24",
  "So do not fear\nfor I am with you\ndo not be dismayed\nfor I am your God.\nI will strengthen you and help you\nI will uphold you\nwith my righteous right hand.\n\nIsaiah 41:10",
  "but those who hope in the LORD\nwill renew their strength.\nThey will soar on wings like eagles\nthey will run\nand not grow weary\nthey will walk and not be faint.\n\nIsaiah 40:31",
  "Jesus looked at them and said\nWith man this is impossible\nbut not with God\nall things are possible\nwith God.\n\nMark 10:27",
  "Cast all your anxiety on him\nbecause he cares for you.\n\n1 Peter 5:7",
  "Jesus looked at them and said\nWith man this is impossible\nbut with God\nall things are possible.\n\nMatthew 19:26",
  "I can do everything\nthrough him\nwho gives me strength.\n\nPhilippians 4:13",
  "Therefore my dear brothers\nstand firm.\nLet nothing move you.\nAlways give yourselves fully\nto the work of the Lord\nbecause you know\nthat your labor in the Lord\nis not in vain.\n\n1 Corinthians 15:58",
  "Do everything\nin love.\n\n1 Corinthians 16:14",
  "you can say to this mountain\nMove from here to there\nand it will move.\nNothing will be impossible\nfor you.\n\nMatthew 17:20",
  "O give thanks unto the LORD,\nfor he is good\nfor his mercy\nendureth for ever.\n\nPsalm 107:1",
  'For I know the plans\nI have for you\ndeclares the LORD\nplans to prosper you\nand not to harm you\nplans to give you\nhope and a future.\n\nJeremiah 29:11',
  "O taste and see\nthat the LORD is good\nblessed is the man\nthat trusteth in him.\n\nPsalm 34:8",
  "And we know that in all things\nGod works for the good of those\nwho love him,\nwho have been called\naccording to his purpose.\n\nRomans 8:28",
  "Trust in the LORD\nwith all your heart\nand lean not\non your own understanding\nin all your ways acknowledge him\nand he will make your paths straight.\n\nProverbs 3:5-6",
  "The name of the LORD\nis a strong tower\nthe righteous run to it\nand are safe.\n\nProverbs 18:10",
  "I have set the LORD\nalways before me\nbecause he is at my right hand,\nI shall not be moved.\n\nPsalm 16:8",
  "Yea, though I walk through\nthe valley of the shadow of death,\nI will fear no evil\nfor thou art with me\nthy rod and thy staff\nthey comfort me.\n\nPsalm 23:4",
  "The LORD of hosts is with us\nthe God of Jacob is our refuge.\n\nPsalm 46:7",
  "Cast thy burden upon the LORD,\nand he shall sustain thee\nhe shall never suffer\nthe righteous to be moved.\n\nPsalm 55:22",
  "He alone is my rock\nand my salvation\nhe is my fortress,\nI will not be shaken.\n\nPsalm 62:6",
  "You are my refuge and my shield\nI have put my hope\nin your word.\nAway from me,\nyou evildoers,\nthat I may keep\nthe commands of my God!\n\nPsalm 119:114-115",
  "My comfort in my suffering is this\nYour promise preserves my life.\n\nPsalm 119:50",
  "I call on the LORD\nin my distress\nand he answers me.\n\nPsalm 120:1",
  "You will keep in perfect peace\nhim whose mind is steadfast\nbecause he trusts in you.\n\nIsaiah 26:3",
  "Come to me\nall you who are weary\nand burdened\nand I will give you rest.\n\nMatthew 11:28",
  "I have told you these things,\nso that in me you may have peace.\nIn this world you will have trouble.\nBut take heart!\nI have overcome the world.\n\nJohn 16:33",
  "Therefore encourage one another\nand build each other up\njust as in fact\nyou are doing.\n\n1 Thessalonians 5:11",
  "And my God will meet\nall your needs\naccording to his glorious riches\nin Christ Jesus.\n\nPhilippians 4:19",
  "The LORD is good\na refuge in times of trouble\nHe cares for those\nwho trust in him\n\nNahum 1:7",
  "One thing I ask of the LORD,\nthis is what I seek\nthat I may dwell in the house of the LORD\nall the days of my life,\nto gaze upon the beauty of the LORD\nand to seek him in his temple.\n\nPsalm 27:4",
  "A friend loves\nat all times\nand a brother is born\nfor adversity.\n\nProverbs 17:17",
  "Now we see\nbut a poor reflection as in a mirror\nthen we shall see\nface to face.\nNow I know in part\nthen I shall know fully\neven as I am fully known.\n\n1 Corinthians 13:12",
  "Be on your guard\nstand firm in the faith\nbe men of courage\nbe strong.\n\n1 Corinthians 16:13",
  "Dear friends, I urge you\nas aliens and strangers\nin the world\nto abstain from sinful desires\nwhich war against your soul.\n\n1 Peter 2:11",
  "and receive from him\nanything we ask,\nbecause we obey his commands\nand do what pleases him.\n\n1 John 3:22",
  "The LORD is my strength and my song\nhe has become my salvation\nHe is my God\nand I will praise him\nmy father's God\nand I will exalt him.\n\nExodus 15:2",
  "Wealth and honor come from you\nyou are the ruler of all things.\nIn your hands are strength\nand power to exalt\nand give strength to all.\n\n1 Chronicles 29:12",
  "The LORD your God is with you\nhe is mighty to save.\nHe will take great delight in you\nhe will quiet you with his love\nhe will rejoice\nover you with singing.\n\nZephaniah 3:17",
  "From the lips of children and infants\nyou have ordained praise\nbecause of your enemies,\nto silence the foe\nand the avenger.\n\nPsalm 8:2",
  "I love you, O LORD, my strength.\nThe LORD is my rock,\nmy fortress and my deliverer\nmy God is my rock\nin whom I take refuge.\nHe is my shield and the horn of my salvation\nmy stronghold.\n\nPsalm 18:1-2",
  "The salvation of the righteous\ncomes from the LORD\nhe is their stronghold\nin time of trouble.\n\nPsalm 37:39",
  "I will come and proclaim\nyour mighty acts,\nO Sovereign LORD\nI will proclaim your righteousness\nyours alone.\n\nPsalm 71:16",
  "My soul is weary with sorrow\nstrengthen me\naccording to your word.\n\nPsalm 119:28",
  "Surely God is my salvation\nI will trust and not be afraid.\nThe LORD, the LORD,\nis my strength and my song\nhe has become my salvation.\n\nIsaiah 12:2",
  "The Sovereign LORD is my strength\nhe makes my feet\nlike the feet of a deer\nhe enables me to go on the heights\nFor the director of music.\nOn my stringed instruments.\n\nHabakkuk 3:19",
  "Therefore do not worry\nabout tomorrow\nfor tomorrow will worry about itself.\nEach day has enough\ntrouble of its own.\n\nMatthew 6:34",
  "Love the Lord your God\nwith all your heart\nand with all your soul\nand with all your mind\nand with all your strength.\n\nMark 12:30",
  "But you will receive power\nwhen the Holy Spirit comes on you\nand you will be my witnesses\nin Jerusalem\nand in all Judea and Samaria\nand to the ends of the earth.\n\nActs 1:8",
  "Therefore we do not lose heart.\nThough outwardly we are wasting away\nyet inwardly\nwe are being renewed\nday by day.\n\n2 Corinthians 4:16",
  "That he would grant you,\naccording to the riches of his glory,\nto be strengthened with\nmight by his Spirit in the inner man\n\nEphesians 3:16",
  "Finally, my brethren,\nbe strong in the Lord,\nand in the power of his might.\n\nEphesians 6:10",
  "being confident of this\nthat he who began a good work\nin you will carry it\non to completion\nuntil the day of Christ Jesus.\n\nPhilippians 1:6",
  "If the LORD delights in a man's way\nhe makes his steps firm\nthough he stumble,\nhe will not fall,\nfor the LORD upholds him\nwith his hand.\n\nPsalm 37:23-24",
  "Do not be afraid\nlittle flock\nfor your Father\nhas been pleased to give you\nthe kingdom.\n\nLuke 12:32",
  "And the peace of God\nwhich transcends all understanding\nwill guard your hearts\nand your minds\nin Christ Jesus.\n\nPhilippians 4:7",
  "We live by faith\nnot by sight.\n\n2 Corinthians 5:7",
  "Fight the good fight of the faith.\nTake hold of the eternal life\nto which you were called\nwhen you made your good confession\nin the presence\nof many witnesses.\n\n1 Timothy 6:12",
  "You, dear children,\nare from God\nand have overcome them,\nbecause the one\nwho is in you\nis greater than the one\nwho is in the world.\n\n1 John 4:4",
  "Praise be to the LORD,\nfor he has heard my cry for mercy.\nThe LORD is my strength and my shield\nmy heart trusts in him,\nand I am helped.\nMy heart leaps for joy\nand I will give thanks to him\nin song.\n\nPsalm 28:6-7",
  "Look to the LORD\nand his strength\nseek his face always.\n\n1 Chronicles 16:11",
  "But the Lord stood at my side\nand gave me strength\nso that through me\nthe message might be\nfully proclaimed\nand all the Gentiles\nmight hear it.\n\n2 Timothy 4:17",
  "The LORD is my strength\nand my song\nhe has become my salvation.\n\nPsalm 118:14",
  "Now faith is being\nsure of what we hope for\nand certain of what\nwe do not see.\n\nHebrews 11:1",
  "We have this hope\nas an anchor for the soul\nfirm and secure.\nIt enters the inner sanctuary\nbehind the curtain\n\nHebrews 6:19",
  "Let us hold\nunswervingly to the hope\nwe profess for he\nwho promised is faithful.\n\nHebrews 10:23",
  "That is why\nfor Christ's sake\nI delight in weaknesses\nin insults, in hardships\nin persecutions, in difficulties.\nFor when I am weak\nthen I am strong.\n\n2 Corinthians 12:10",
  "For\nnothing is\nimpossible\nwith God.\n\nLuke 1:37",
  "Rise up\nthis matter is in your hands\nWe will support you\nso take courage\nand do it.\n\nEzra 10:4",
  "In the beginning God\ncreated the heavens\nand the earth.\n\nGenesis 1:1",
  "Do not steal.\nDo not lie.\nDo not deceive\none another.\n\nLeviticus 19:11",
  'God is not a man\nthat he should lie\nnor a son of man\nthat he should change his mind.\nDoes he speak\nand then not act?\nDoes he promise\nand not fulfill?\n\nNumbers 23:19',
  "When I am afraid\nI will trust in you.\n\nPsalm 56:3",
  "Sing to the LORD,\npraise his name\nproclaim his salvation\nday after day.\n\nPsalm 96:2",
  "How can a young man\nkeep his way pure?\nBy living according to your word.\n\nPsalm 119:9",
  "I have hidden your word\nin my heart\nthat I might not sin\nagainst you.\n\nPsalm 119:11",
  "Great is our Lord\nand mighty in power\nhis understanding\nhas no limit.\n\nPsalm 147:5",
  "Honor the LORD with your wealth\nwith the firstfruits\nof all your crops\nthen your barns will be\nfilled to overflowing\nand your vats will brim\nover with new wine.\n\nProverbs 3:9-10",
  "We all like sheep\nhave gone astray\neach of us has turned to his own way\nand the LORD has laid on him\nthe iniquity of us all.\n\nIsaiah 53:6",
  'She will give\nbirth to a son\nand you are to give him\nthe name Jesus\nbecause he will save his people\nfrom their sins.\n\nMatthew 1:21',
  'Come, follow me\nJesus said\nand I will make you\nfishers of men.\n\nMatthew 4:19',
  'In the same way\nlet your light shine before men\nthat they may see your good\ndeeds and praise\nyour Father in heaven.\n\nMatthew 5:16',
  'He who is not with me\nis against me\nand he who does not gather\nwith me scatters.\n\nMatthew 12:30',
  'For where two or three\ncome together in my name\nthere am I with them.\n\nMatthew 18:20',
  'For even the Son of Man\ndid not come to be served\nbut to serve\nand to give his life\nas a ransom for many.\n\nMark 10:45',
  'No one knows\nabout that day or hour\nnot even the angels in heaven\nnor the Son\nbut only the Father.\nBe on guard!\nBe alert!\nYou do not know\nwhen that time will come.\n\nMark 13:32-33',
  'He said to them\nGo into all the world\nand preach the good news\nto all creation.\n\nMark 16:15',
  'Then he said to them all\nIf anyone would come after me\nhe must deny himself\nand take up his cross\ndaily and follow me.\n\nLuke 9:23',
  'He replied\nBlessed rather are those\nwho hear the word of God\nand obey it.\n\nLuke 11:28',
  'Whoever can be trusted\nwith very little can\nalso be trusted with much\nand whoever is dishonest\nwith very little will\nalso be dishonest with much.\n\nLuke 16:10',
  'No servant can serve two masters.\nEither he will hate the one\nand love the other\nor he will be devoted to the one\nand despise the other.\nYou cannot serve\nboth God and Money.\n\nLuke 16:13',
  "But as many as received him,\nto them gave he power to become the sons of God,\neven to them that believe on his name\n\nJohn 1:12",
  'He that believeth on the Son hath everlasting life\nand he that believeth not the Son shall not see life\nbut the wrath of God abideth on him.\n\nJohn 3:36',
  'Verily, verily, I say unto you,\nHe that heareth my word, and believeth on him that sent me,\nhath everlasting life, and shall not come into condemnation\nbut is passed from death unto life.\n\nJohn 5:24',
  'A new commandment I give unto you,\nThat ye love one another as I have loved you,\nthat ye also love one another.\nBy this shall all men know that ye are my disciples,\nif ye have love one to another.\n\nJohn 13:34-35',
  'Jesus saith unto him,\nI am the way, the truth, and the life\nno man cometh unto the Father, but by me.\n\nJohn 14:6',
  'He that hath my commandments, and keepeth them,\nhe it is that loveth me\nand he that loveth me shall be loved of my Father,\nand I will love him,\nand will manifest myself to him.\n\nJohn 14:21',
  'If ye abide in me,\nand my words abide in you,\nye shall ask what ye will,\nand it shall be done unto you.\n\nJohn 15:7',
  'Sanctify them\nthrough thy truth\nthy word is truth.\n\nJohn 17:17',
  "But these are written,\nthat ye might believe\nthat Jesus is the Christ, the Son of God\nand that believing ye\nmight have life through his name.\n\nJohn 20:31",
  'Salvation is found\nin no one else\nfor there is no other name\nunder heaven given to men\nby which we must be saved.\n\nActs 4:12',
  'So I strive always to keep\nmy conscience clear\nbefore God and man.\n\nActs 24:16',
  "I am not ashamed of the gospel,\nbecause it is the power of God\nfor the salvation of everyone\nwho believes\nfirst for the Jew,nthen for the Gentile.\n\nRomans 1:16",
  "for all have sinned\nand fall short of\nthe glory of God\n\nRomans 3:23",
  "being fully persuaded\nthat God had power\nto do what he had promised.\n\nRomans 4:21",
  "Therefore\nsince we have been justified through faith\nwe have peace with God\nthrough our Lord Jesus Christ\n\nRomans 5:1",
  "But God demonstrates\nhis own love for us in this\nWhile we were still sinners\nChrist died for us.\n\nRomans 5:8",
  "Therefore\njust as sin entered the world\nthrough one man,\nand death through sin,\nand in this way death\ncame to all men\nbecause all sinned\n\nRomans 5:12",
  "What shall we say, then?\nShall we go on sinning\nso that grace may increase?\nBy no means!\nWe died to sin\nhow can we live\nin it any longer?\n\nRomans 6:1-2",
  "For sin shall not be your master\nbecause you are not under law\nbut under grace.\n\nRomans 6:14",
  "For the wages of sin is death\nbut the gift of God\nis eternal life\nin Christ Jesus our Lord.\n\nRomans 6:23",
  "Therefore\nthere is now no condemnation\nfor those who are\nin Christ Jesus\n\nRomans 8:1",
  "He who did not spare his own Son\nbut gave him up for us\nall--how will he not also\nalong with him\ngraciously give us all things?\n\nRomans 8:32",
  'for Everyone\nwho calls on the name\nof the Lord\nwill be saved.\n\nRomans 10:13',
  "Consequently\nfaith comes from hearing the message\nand the message is heard\nthrough the word of Christ.\n\nRomans 10:17",
  "And if by grace\nthen it is no longer by works\nif it were\ngrace would no longer be grace.\n\nRomans 11:6",
  "Do not repay anyone\nevil for evil.\nBe careful to do\nwhat is right\nin the eyes of everybody.\n\nRomans 12:17",
  "If it is possible\nas far as it depends on you\nlive at peace\nwith everyone.\n\nRomans 12:18",
  "Everyone must submit\nhimself to the governing authorities\nfor there is no authority\nexcept that which God\nhas established.\nThe authorities that exist\nhave been established by God.\n\nRomans 13:1",
  "Accept one another, then\njust as Christ accepted you\nin order to bring praise to God.\n\nRomans 15:7",
  "For the message of the cross\nis foolishness to those\nwho are perishing\nbut to us who are being saved it\nis the power of God.\n\n1 Corinthians 1:18",
  'Therefore as it is written\nLet him who boasts\nboast in the Lord.\n\n1 Corinthians 1:31',
  "We have not received\nthe spirit of the world\nbut the Spirit\nwho is from God\nthat we may understand\nwhat God has freely given us.\n\n1 Corinthians 2:12",
  "Don't you know that you\nyourselves are God's temple\nand that God's Spirit\nlives in you?\n\n1 Corinthians 3:16",
  "you were bought at a price.\nTherefore honor\nGod with your body.\n\n1 Corinthians 6:20",
  'Do not be misled\nBad company corrupts\ngood character.\n\n1 Corinthians 15:33',
  "For we do not preach ourselves\nbut Jesus Christ as Lord\nand ourselves as your servants\nfor Jesus' sake.\n\n2 Corinthians 4:5",
  "Therefore\nif anyone is in Christ\nhe is a new creation\nthe old has gone\nthe new has come!\n\n2 Corinthians 5:17",
  "Do not be yoked\ntogether with unbelievers.\nFor what do righteousness\nand wickedness have in common?\nOr what fellowship can light\nhave with darkness?\n\n2 Corinthians 6:14",
  "Examine yourselves to see\nwhether you are in the faith\ntest yourselves.\nDo you not realize\nthat Christ Jesus is in you--unless\nof course\nyou fail the test?\n\n2 Corinthians 13:5",
  "I have been crucified\nwith Christ and I no longer live\nbut Christ lives in me.\nThe life I live in the body\nI live by faith\nin the Son of God\nwho loved me\nand gave himself for me.\n\nGalatians 2:20",
  "But the fruit of the Spirit\nis love, joy, peace,\npatience, kindness,\ngoodness, faithfulness\ngentleness and self-control.\nAgainst such things\nthere is no law.\n\nGalatians 5:22-23",
  "Do not be deceived\nGod cannot be mocked.\nA man reaps\nwhat he sows.\n\nGalatians 6:7",
  "In whom we have redemption through his blood,\nthe forgiveness of sins,\naccording to the riches of his grace\n\nEphesians 1:7",
  "Let no corrupt communication\nproceed out of your mouth,\nbut that which is good\nto the use of edifying,\nthat it may minister grace\nunto the hearers.\n\nEphesians 4:29",
  "And be ye kind one to another,\ntenderhearted, forgiving one another,\neven as God for Christ's sake\nhath forgiven you.\n\nEphesians 4:32",
  'Children,\nobey your parents in the Lord for this is right.\nHonour thy father and mother\nwhich is the first commandment with promise\nThat it may be well with thee,\nand thou mayest live long on the earth.\n\nEphesians 6:1-3',
  "For to me\nto live is Christ\nand to die is gain.\n\nPhilippians 1:21",
  "But our citizenship is in heaven.\nAnd we eagerly await\na Savior from there\nthe Lord Jesus Christ\n\nPhilippians 3:20",
  "Devote\nyourselves to prayer\nbeing watchful\nand thankful.\n\nColossians 4:2",
  "Be joyful always\npray continually\ngive thanks in all circumstances\nfor this is God's will for you\nin Christ Jesus.\n\n1 Thessalonians 5:16-18",
  "For there is one God\nand one mediator\nbetween God and men\nthe man Christ Jesus\n\n1 Timothy 2:5",
  "If anyone does not provide\nfor his relatives\nand especially for his immediate family\nhe has denied the faith\nand is worse\nthan an unbeliever.\n\n1 Timothy 5:8",
  "What you heard from me\nkeep as the pattern\nof sound teaching\nwith faith and love\nin Christ Jesus.\n\n2 Timothy 1:13",
  "Guard the good deposit\nthat was entrusted to you--guard\nit with the help\nof the Holy Spirit\nwho lives in us.\n\n2 Timothy 1:14",
  "Do your best to present\nyourself to God\nas one approved a workman\nwho does not need to be ashamed\nand who correctly handles\nthe word of truth.\n\n2 Timothy 2:15",
  "Nevertheless\nGod's solid foundation stands firm\nsealed with this inscription\nThe Lord knows those\nwho are his\nand Everyone who confesses\nthe name of the Lord\nmust turn away\nfrom wickedness.\n\n2 Timothy 2:19",
  "In fact\neveryone who wants to live\na godly life\nin Christ Jesus\nwill be persecuted\n\n2 Timothy 3:12",
  "he saved us\nnot because of righteous things\nwe had done\nbut because of his mercy.\nHe saved us\nthrough the washing of rebirth\nand renewal by\nthe Holy Spirit\n\nTitus 3:5",
  "Because he himself suffered\nwhen he was tempted\nhe is able to help those\nwho are being tempted.\n\nHebrews 2:18",
  "Let us then approach\nthe throne of grace\nwith confidence\nso that we may receive mercy\nand find grace to help us\nin our time of need.\n\nHebrews 4:16",
  "Therefore he is able to save\ncompletely those who come to God\nthrough him\nbecause he always lives\nto intercede for them.\n\nHebrews 7:25",
  "And without faith\nit is impossible to please God\nbecause anyone who comes to him\nmust believe that he exists\nand that he rewards those\nwho earnestly seek him.\n\nHebrews 11:6",
  "Consider him who endured\nsuch opposition from sinful men\nso that you will not grow\nweary and lose heart.\n\nHebrews 12:3",
  'Keep your lives free\nfrom the love of money\nand be content with\nwhat you have\nbecause God has said\nNever will I leave you\nnever will I forsake you.\n\nHebrews 13:5',
  "Blessed is the man\nwho perseveres under trial\nbecause when he has stood the test\nhe will receive\nthe crown of life\nthat God has promised to\nthose who love him.\n\nJames 1:12",
  "Do not merely listen to the word\nand so deceive yourselves.\nDo what it says.\n\nJames 1:22",
  "If anyone considers\nhimself religious\nand yet does not keep\na tight rein on his tongue\nhe deceives himself\nand his religion is worthless.\n\nJames 1:26",
  "For whoever keeps the whole law\nand yet stumbles\nat just one point\nis guilty of breaking\nall of it.\n\nJames 2:10",
  "As the body without\nthe spirit is dead\nso faith without\ndeeds is dead.\n\nJames 2:26",
  "Anyone, then\nwho knows the good\nhe ought to do\nand doesn't do it\nsins.\n\nJames 4:17",
  "Like newborn babies\ncrave pure spiritual milk\nso that by it\nyou may grow up\nin your salvation\n\n1 Peter 2:2",
  "For Christ died for sins\nonce for all\nthe righteous for the unrighteous\nto bring you to God.\nHe was put to death in the body\nbut made alive by the Spirit\n\n1 Peter 3:18",
  "If we confess our sins,\nhe is faithful and just\nand will forgive us our sins\nand purify us\nfrom all unrighteousness.\n\n1 John 1:9",
  "Do not be surprised,\nmy brothers,\nif the world hates you.\n\n1 John 3:13",
  "Dear children,\nlet us not love\nwith words or tongue\nbut with actions\nand in truth.\n\n1 John 3:18",
  "Do not grieve, for the joy of the Lord is your strength. Nehemiah 8:10",
  "The LORD is a refuge\nfor the oppressed\na stronghold in times\nof trouble.\n\nPsalm 9:9",
  "The lions may grow\nweak and hungry,\nbut those who seek the LORD\nlack no good thing.\n\nPsalm 34:10",
  "Trust in the LORD forever\nfor the LORD, the LORD\nis the Rock eternal.\n\nIsaiah 26:4",
  "You are my hiding place\nyou will protect me\nfrom trouble\nand surround me\nwith songs of deliverance.\n\nPsalm 32:7",
  "The LORD replied\nMy Presence will go with you\nand I will give you rest.\n\nExodus 33:14",
  "And the LORD,\nhe it is that doth go before thee\nhe will be with thee,\nhe will not fail thee,\nneither forsake thee\nfear not,\nneither be dismayed.\n\nDeuteronomy 31:8",
  "The eternal God is thy refuge,\nand underneath are the everlasting arms\nand he shall thrust out\nthe enemy from before thee\nand shall say, Destroy them.\n\nDeuteronomy 33:27",
  "The righteous cry out,\nand the LORD hears them\nhe delivers them\nfrom all their troubles.\n\nPsalm 34:17",
  "In repentance and rest\nis your salvation\nin quietness and trust\nis your strength\nbut you would have none of it.\n\nIsaiah 30:15",
  "Who of you\nby worrying can\nadd a single hour to his life?\nSince you cannot do\nthis very little thing\nwhy do you worry\nabout the rest?\n\nLuke 12:25-26",
  "Peace I leave with you,\nmy peace I give unto you not as the world giveth,\ngive I unto you.\nLet not your heart be troubled,\nneither let it be afraid.\n\nJohn 14:27",
  "I sought the LORD,\nand he answered me\nhe delivered me\nfrom all my fears.\n\nPsalm 34:4",
  "Have I not commanded you?\nBe strong and courageous.\nDo not be terrified\ndo not be discouraged\nfor the LORD your God\nwill be with you\nwherever you go.\n\nJoshua 1:9",
  "The LORD is near\nto all who call on him,\nto all who call\non him in truth.\nHe fulfills the desires of those\nwho fear him\nhe hears their cry\nand saves them.\n\nPsalm 145:18-19",
  "For God did not give us\na spirit of timidity\nbut a spirit of power\nof love\nand of self-discipline.\n\n2 Timothy 1:7",
  "When I called,\nyou answered me\nyou made me bold\nand stouthearted.\n\nPsalm 138:3",
  "My soul finds rest in God alone\nmy salvation comes from him.\nHe alone is my rock\nand my salvation\nhe is my fortress,\nI will never be shaken.\n\nPsalm 62:1-2",
  "Praise the LORD.\nBlessed is the man\nwho fears the LORD,\nwho finds great delight\nin his commands.\n\nPsalm 112:1",
  "I will say of the LORD\nHe is my refuge\nand my fortress\nmy God in whom I trust.\n\nPsalm 91:2",
  "My grace is sufficient\nfor you\nfor my power\nis made perfect\nin weakness.\n\n2 Corinthians 12:9",
  "But the Lord is faithful\nand he will strengthen\nand protect you\nfrom the evil one.\n\n2 Thessalonians 3:3",
  "He gives strength\nto the weary\nand increases the power\nof the weak.\n\nIsaiah 40:29",
  "And the God of all grace\nwho called you\nto his eternal glory in Christ\nafter you have suffered\na little while\nwill himself restore you\nand make you strong\nfirm and steadfast.\n\n1 Peter 5:10",
  "Now may the Lord of peace himself\ngive you peace at all times\nand in every way.\nThe Lord be with\nall of you.\n\n2 Thessalonians 3:16",
];
List<String> _koreanVerse = [];

int verseNum = 0;

class VerseData {
  String getEnglish() {
    return _englishVerse[verseNum];
  }

  String getKorean() {
    return _koreanVerse[verseNum];
  }
}
