import 'dart:math';

List<String> _englishVerse = [
  'For this is the reason\nthe gospel was preached even to\nthose who are now dead,\nso that they might be judged\naccording to men in regard to the body,\nbut live according to God\nin regard to the spirit.\n\n1 Peter 4:6',
  "Because of the LORD's great love\nwe are not consumed,\nfor his compassions never fail.\nThey are new every morning\ngreat is your faithfulness.\n\nLamentations 3:22-23",
  "Greater love has no one than this,\nthat he lay down his life for his friends.\n\nJohn 15:13",
  "Now unto him\nthat is able to do exceeding\nabundantly above all that we ask or think,\naccording to the power\nthat worketh in us\n\nEphesians 3:20",
  "Be strong and of a good courage,\nfear not, nor be afraid of them\nfor the LORD thy God,\nhe it is that doth go with thee\nhe will not fail thee,\nnor forsake thee.\n\nDeuteronomy 31:6",
  "The LORD is my light\nand my salvation\nwhom shall I fear?\nthe LORD is the strength of my life\nof whom shall I be afraid?\n\nPsalm 27:1",
  "There is no fear in love.\nBut perfect love drives out fear,\nbecause fear has to do with punishment.\nThe one who fears\nis not made perfect in love.\n\n1 John 4:18",
  "What, then, shall we say\nin response to this?\nIf God is for us,\nwho can be against us?\n\nRomans 8:31",
  "May the God of hope\nfill you with all joy and peace\nas you trust in him,\nso that you may overflow\nwith hope by\nthe power of the Holy Spirit.\n\nRomans 15:13",
  "Be of good courage,\nand he shall strengthen your heart,\nall ye that hope in the LORD.\n\nPsalm 31:24",
  "So do not fear\nfor I am with you\ndo not be dismayed\nfor I am your God.\nI will strengthen you and help you\nI will uphold you\nwith my righteous right hand.\n\nIsaiah 41:10",
  "but those who hope in the LORD\nwill renew their strength.\nThey will soar on wings like eagles\nthey will run\nand not grow weary\nthey will walk and not be faint.\n\nIsaiah 40:31",
  "Jesus looked at them and said\nWith man this is impossible\nbut not with God\nall things are possible\nwith God.\n\nMark 10:27",
  "Cast all your anxiety on him\nbecause he cares for you.\n\n1 Peter 5:7",
  "Jesus looked at them and said\nWith man this is impossible\nbut with God\nall things are possible.\n\nMatthew 19:26",
  "I can do everything\nthrough him\nwho gives me strength.\n\nPhilippians 4:13",
  "Therefore my dear brothers\nstand firm.\nLet nothing move you.\nAlways give yourselves fully\nto the work of the Lord\nbecause you know\nthat your labor in the Lord\nis not in vain.\n\n1 Corinthians 15:58",
  "Do everything\nin love.\n\n1 Corinthians 16:14",
  "you can say to this mountain\nMove from here to there\nand it will move.\nNothing will be impossible\nfor you.\n\nMatthew 17:20",
  "O give thanks unto the LORD,\nfor he is good\nfor his mercy\nendureth for ever.\n\nPsalm 107:1",
  'For I know the plans\nI have for you\ndeclares the LORD\nplans to prosper you\nand not to harm you\nplans to give you\nhope and a future.\n\nJeremiah 29:11',
  "O taste and see\nthat the LORD is good\nblessed is the man\nthat trusteth in him.\n\nPsalm 34:8",
  "And we know that in all things\nGod works for the good of those\nwho love him,\nwho have been called\naccording to his purpose.\n\nRomans 8:28",
  "Trust in the LORD\nwith all your heart\nand lean not\non your own understanding\nin all your ways acknowledge him\nand he will make your paths straight.\n\nProverbs 3:5-6",
  "The name of the LORD\nis a strong tower\nthe righteous run to it\nand are safe.\n\nProverbs 18:10",
  "I have set the LORD\nalways before me\nbecause he is at my right hand,\nI shall not be moved.\n\nPsalm 16:8",
  "Yea, though I walk through\nthe valley of the shadow of death,\nI will fear no evil\nfor thou art with me\nthy rod and thy staff\nthey comfort me.\n\nPsalm 23:4",
  "The LORD of hosts is with us\nthe God of Jacob is our refuge.\n\nPsalm 46:7",
  "Cast thy burden upon the LORD,\nand he shall sustain thee\nhe shall never suffer\nthe righteous to be moved.\n\nPsalm 55:22",
  "He alone is my rock\nand my salvation\nhe is my fortress,\nI will not be shaken.\n\nPsalm 62:6",
  "You are my refuge and my shield\nI have put my hope\nin your word.\nAway from me,\nyou evildoers,\nthat I may keep\nthe commands of my God!\n\nPsalm 119:114-115",
  "My comfort in my suffering is this\nYour promise preserves my life.\n\nPsalm 119:50",
  "I call on the LORD\nin my distress\nand he answers me.\n\nPsalm 120:1",
  "You will keep in perfect peace\nhim whose mind is steadfast\nbecause he trusts in you.\n\nIsaiah 26:3",
  "Come to me\nall you who are weary\nand burdened\nand I will give you rest.\n\nMatthew 11:28",
  "I have told you these things,\nso that in me you may have peace.\nIn this world you will have trouble.\nBut take heart!\nI have overcome the world.\n\nJohn 16:33",
  "Therefore encourage one another\nand build each other up\njust as in fact\nyou are doing.\n\n1 Thessalonians 5:11",
  "And my God will meet\nall your needs\naccording to his glorious riches\nin Christ Jesus.\n\nPhilippians 4:19",
  "The LORD is good\na refuge in times of trouble\nHe cares for those\nwho trust in him\n\nNahum 1:7",
  "One thing I ask of the LORD,\nthis is what I seek\nthat I may dwell in the house of the LORD\nall the days of my life,\nto gaze upon the beauty of the LORD\nand to seek him in his temple.\n\nPsalm 27:4",
  "A friend loves\nat all times\nand a brother is born\nfor adversity.\n\nProverbs 17:17",
  "Now we see\nbut a poor reflection as in a mirror\nthen we shall see\nface to face.\nNow I know in part\nthen I shall know fully\neven as I am fully known.\n\n1 Corinthians 13:12",
  "Be on your guard\nstand firm in the faith\nbe men of courage\nbe strong.\n\n1 Corinthians 16:13",
  "Dear friends, I urge you\nas aliens and strangers\nin the world\nto abstain from sinful desires\nwhich war against your soul.\n\n1 Peter 2:11",
  "and receive from him\nanything we ask,\nbecause we obey his commands\nand do what pleases him.\n\n1 John 3:22",
  "The LORD is my strength and my song\nhe has become my salvation\nHe is my God\nand I will praise him\nmy father's God\nand I will exalt him.\n\nExodus 15:2",
  "Wealth and honor come from you\nyou are the ruler of all things.\nIn your hands are strength\nand power to exalt\nand give strength to all.\n\n1 Chronicles 29:12",
  "The LORD your God is with you\nhe is mighty to save.\nHe will take great delight in you\nhe will quiet you with his love\nhe will rejoice\nover you with singing.\n\nZephaniah 3:17",
  "From the lips of children and infants\nyou have ordained praise\nbecause of your enemies,\nto silence the foe\nand the avenger.\n\nPsalm 8:2",
  "I love you, O LORD, my strength.\nThe LORD is my rock,\nmy fortress and my deliverer\nmy God is my rock\nin whom I take refuge.\nHe is my shield and the horn of my salvation\nmy stronghold.\n\nPsalm 18:1-2",
  "The salvation of the righteous\ncomes from the LORD\nhe is their stronghold\nin time of trouble.\n\nPsalm 37:39",
  "I will come and proclaim\nyour mighty acts,\nO Sovereign LORD\nI will proclaim your righteousness\nyours alone.\n\nPsalm 71:16",
  "My soul is weary with sorrow\nstrengthen me\naccording to your word.\n\nPsalm 119:28",
  "Surely God is my salvation\nI will trust and not be afraid.\nThe LORD, the LORD,\nis my strength and my song\nhe has become my salvation.\n\nIsaiah 12:2",
  "The Sovereign LORD is my strength\nhe makes my feet\nlike the feet of a deer\nhe enables me to go on the heights\nFor the director of music.\nOn my stringed instruments.\n\nHabakkuk 3:19",
  "Therefore do not worry\nabout tomorrow\nfor tomorrow will worry about itself.\nEach day has enough\ntrouble of its own.\n\nMatthew 6:34",
  "Love the Lord your God\nwith all your heart\nand with all your soul\nand with all your mind\nand with all your strength.\n\nMark 12:30",
  "But you will receive power\nwhen the Holy Spirit comes on you\nand you will be my witnesses\nin Jerusalem\nand in all Judea and Samaria\nand to the ends of the earth.\n\nActs 1:8",
  "Therefore we do not lose heart.\nThough outwardly we are wasting away\nyet inwardly\nwe are being renewed\nday by day.\n\n2 Corinthians 4:16",
  "That he would grant you,\naccording to the riches of his glory,\nto be strengthened with\nmight by his Spirit in the inner man\n\nEphesians 3:16",
  "Finally, my brethren,\nbe strong in the Lord,\nand in the power of his might.\n\nEphesians 6:10",
  "being confident of this\nthat he who began a good work\nin you will carry it\non to completion\nuntil the day of Christ Jesus.\n\nPhilippians 1:6",
  "If the LORD delights in a man's way\nhe makes his steps firm\nthough he stumble,\nhe will not fall,\nfor the LORD upholds him\nwith his hand.\n\nPsalm 37:23-24",
  "Do not be afraid\nlittle flock\nfor your Father\nhas been pleased to give you\nthe kingdom.\n\nLuke 12:32",
  "And the peace of God\nwhich transcends all understanding\nwill guard your hearts\nand your minds\nin Christ Jesus.\n\nPhilippians 4:7",
  "We live by faith\nnot by sight.\n\n2 Corinthians 5:7",
  "Fight the good fight of the faith.\nTake hold of the eternal life\nto which you were called\nwhen you made your good confession\nin the presence\nof many witnesses.\n\n1 Timothy 6:12",
  "You, dear children,\nare from God\nand have overcome them,\nbecause the one\nwho is in you\nis greater than the one\nwho is in the world.\n\n1 John 4:4",
  "Praise be to the LORD,\nfor he has heard my cry for mercy.\nThe LORD is my strength and my shield\nmy heart trusts in him,\nand I am helped.\nMy heart leaps for joy\nand I will give thanks to him\nin song.\n\nPsalm 28:6-7",
  "Look to the LORD\nand his strength\nseek his face always.\n\n1 Chronicles 16:11",
  "But the Lord stood at my side\nand gave me strength\nso that through me\nthe message might be\nfully proclaimed\nand all the Gentiles\nmight hear it.\n\n2 Timothy 4:17",
  "The LORD is my strength\nand my song\nhe has become my salvation.\n\nPsalm 118:14",
  "Now faith is being\nsure of what we hope for\nand certain of what\nwe do not see.\n\nHebrews 11:1",
  "We have this hope\nas an anchor for the soul\nfirm and secure.\nIt enters the inner sanctuary\nbehind the curtain\n\nHebrews 6:19",
  "Let us hold\nunswervingly to the hope\nwe profess for he\nwho promised is faithful.\n\nHebrews 10:23",
  "That is why\nfor Christ's sake\nI delight in weaknesses\nin insults, in hardships\nin persecutions, in difficulties.\nFor when I am weak\nthen I am strong.\n\n2 Corinthians 12:10",
  "For\nnothing is\nimpossible\nwith God.\n\nLuke 1:37",
  "Rise up\nthis matter is in your hands\nWe will support you\nso take courage\nand do it.\n\nEzra 10:4",
  "In the beginning God\ncreated the heavens\nand the earth.\n\nGenesis 1:1",
  "Do not steal.\nDo not lie.\nDo not deceive\none another.\n\nLeviticus 19:11",
  'God is not a man\nthat he should lie\nnor a son of man\nthat he should change his mind.\nDoes he speak\nand then not act?\nDoes he promise\nand not fulfill?\n\nNumbers 23:19',
  "When I am afraid\nI will trust in you.\n\nPsalm 56:3",
  "Sing to the LORD,\npraise his name\nproclaim his salvation\nday after day.\n\nPsalm 96:2",
  "How can a young man\nkeep his way pure?\nBy living according to your word.\n\nPsalm 119:9",
  "I have hidden your word\nin my heart\nthat I might not sin\nagainst you.\n\nPsalm 119:11",
  "Great is our Lord\nand mighty in power\nhis understanding\nhas no limit.\n\nPsalm 147:5",
  "Honor the LORD with your wealth\nwith the firstfruits\nof all your crops\nthen your barns will be\nfilled to overflowing\nand your vats will brim\nover with new wine.\n\nProverbs 3:9-10",
  "We all like sheep\nhave gone astray\neach of us has turned to his own way\nand the LORD has laid on him\nthe iniquity of us all.\n\nIsaiah 53:6",
  'She will give\nbirth to a son\nand you are to give him\nthe name Jesus\nbecause he will save his people\nfrom their sins.\n\nMatthew 1:21',
  'Come, follow me\nJesus said\nand I will make you\nfishers of men.\n\nMatthew 4:19',
  'In the same way\nlet your light shine before men\nthat they may see your good\ndeeds and praise\nyour Father in heaven.\n\nMatthew 5:16',
  'He who is not with me\nis against me\nand he who does not gather\nwith me scatters.\n\nMatthew 12:30',
  'For where two or three\ncome together in my name\nthere am I with them.\n\nMatthew 18:20',
  'For even the Son of Man\ndid not come to be served\nbut to serve\nand to give his life\nas a ransom for many.\n\nMark 10:45',
  'No one knows\nabout that day or hour\nnot even the angels in heaven\nnor the Son\nbut only the Father.\nBe on guard!\nBe alert!\nYou do not know\nwhen that time will come.\n\nMark 13:32-33',
  'He said to them\nGo into all the world\nand preach the good news\nto all creation.\n\nMark 16:15',
  'Then he said to them all\nIf anyone would come after me\nhe must deny himself\nand take up his cross\ndaily and follow me.\n\nLuke 9:23',
  'He replied\nBlessed rather are those\nwho hear the word of God\nand obey it.\n\nLuke 11:28',
  'Whoever can be trusted\nwith very little can\nalso be trusted with much\nand whoever is dishonest\nwith very little will\nalso be dishonest with much.\n\nLuke 16:10',
  'No servant can serve two masters.\nEither he will hate the one\nand love the other\nor he will be devoted to the one\nand despise the other.\nYou cannot serve\nboth God and Money.\n\nLuke 16:13',
  "But as many as received him,\nto them gave he power to become the sons of God,\neven to them that believe on his name\n\nJohn 1:12",
  'He that believeth on the Son hath everlasting life\nand he that believeth not the Son shall not see life\nbut the wrath of God abideth on him.\n\nJohn 3:36',
  'Verily, verily, I say unto you,\nHe that heareth my word, and believeth on him that sent me,\nhath everlasting life, and shall not come into condemnation\nbut is passed from death unto life.\n\nJohn 5:24',
  'A new commandment I give unto you,\nThat ye love one another as I have loved you,\nthat ye also love one another.\nBy this shall all men know that ye are my disciples,\nif ye have love one to another.\n\nJohn 13:34-35',
  'Jesus saith unto him,\nI am the way, the truth, and the life\nno man cometh unto the Father, but by me.\n\nJohn 14:6',
  'He that hath my commandments, and keepeth them,\nhe it is that loveth me\nand he that loveth me shall be loved of my Father,\nand I will love him,\nand will manifest myself to him.\n\nJohn 14:21',
  'If ye abide in me,\nand my words abide in you,\nye shall ask what ye will,\nand it shall be done unto you.\n\nJohn 15:7',
  'Sanctify them\nthrough thy truth\nthy word is truth.\n\nJohn 17:17',
  "But these are written,\nthat ye might believe\nthat Jesus is the Christ, the Son of God\nand that believing ye\nmight have life through his name.\n\nJohn 20:31",
  'Salvation is found\nin no one else\nfor there is no other name\nunder heaven given to men\nby which we must be saved.\n\nActs 4:12',
  'So I strive always to keep\nmy conscience clear\nbefore God and man.\n\nActs 24:16',
  "I am not ashamed of the gospel,\nbecause it is the power of God\nfor the salvation of everyone\nwho believes\nfirst for the Jew,nthen for the Gentile.\n\nRomans 1:16",
  "for all have sinned\nand fall short of\nthe glory of God\n\nRomans 3:23",
  "being fully persuaded\nthat God had power\nto do what he had promised.\n\nRomans 4:21",
  "Therefore\nsince we have been justified through faith\nwe have peace with God\nthrough our Lord Jesus Christ\n\nRomans 5:1",
  "But God demonstrates\nhis own love for us in this\nWhile we were still sinners\nChrist died for us.\n\nRomans 5:8",
  "Therefore\njust as sin entered the world\nthrough one man,\nand death through sin,\nand in this way death\ncame to all men\nbecause all sinned\n\nRomans 5:12",
  "What shall we say, then?\nShall we go on sinning\nso that grace may increase?\nBy no means!\nWe died to sin\nhow can we live\nin it any longer?\n\nRomans 6:1-2",
  "For sin shall not be your master\nbecause you are not under law\nbut under grace.\n\nRomans 6:14",
  "For the wages of sin is death\nbut the gift of God\nis eternal life\nin Christ Jesus our Lord.\n\nRomans 6:23",
  "Therefore\nthere is now no condemnation\nfor those who are\nin Christ Jesus\n\nRomans 8:1",
  "He who did not spare his own Son\nbut gave him up for us\nall--how will he not also\nalong with him\ngraciously give us all things?\n\nRomans 8:32",
  'for Everyone\nwho calls on the name\nof the Lord\nwill be saved.\n\nRomans 10:13',
  "Consequently\nfaith comes from hearing the message\nand the message is heard\nthrough the word of Christ.\n\nRomans 10:17",
  "And if by grace\nthen it is no longer by works\nif it were\ngrace would no longer be grace.\n\nRomans 11:6",
  "Do not repay anyone\nevil for evil.\nBe careful to do\nwhat is right\nin the eyes of everybody.\n\nRomans 12:17",
  "If it is possible\nas far as it depends on you\nlive at peace\nwith everyone.\n\nRomans 12:18",
  "Everyone must submit\nhimself to the governing authorities\nfor there is no authority\nexcept that which God\nhas established.\nThe authorities that exist\nhave been established by God.\n\nRomans 13:1",
  "Accept one another, then\njust as Christ accepted you\nin order to bring praise to God.\n\nRomans 15:7",
  "For the message of the cross\nis foolishness to those\nwho are perishing\nbut to us who are being saved it\nis the power of God.\n\n1 Corinthians 1:18",
  'Therefore as it is written\nLet him who boasts\nboast in the Lord.\n\n1 Corinthians 1:31',
  "We have not received\nthe spirit of the world\nbut the Spirit\nwho is from God\nthat we may understand\nwhat God has freely given us.\n\n1 Corinthians 2:12",
  "Don't you know that you\nyourselves are God's temple\nand that God's Spirit\nlives in you?\n\n1 Corinthians 3:16",
  "you were bought at a price.\nTherefore honor\nGod with your body.\n\n1 Corinthians 6:20",
  'Do not be misled\nBad company corrupts\ngood character.\n\n1 Corinthians 15:33',
  "For we do not preach ourselves\nbut Jesus Christ as Lord\nand ourselves as your servants\nfor Jesus' sake.\n\n2 Corinthians 4:5",
  "Therefore\nif anyone is in Christ\nhe is a new creation\nthe old has gone\nthe new has come!\n\n2 Corinthians 5:17",
  "Do not be yoked\ntogether with unbelievers.\nFor what do righteousness\nand wickedness have in common?\nOr what fellowship can light\nhave with darkness?\n\n2 Corinthians 6:14",
  "Examine yourselves to see\nwhether you are in the faith\ntest yourselves.\nDo you not realize\nthat Christ Jesus is in you--unless\nof course\nyou fail the test?\n\n2 Corinthians 13:5",
  "I have been crucified\nwith Christ and I no longer live\nbut Christ lives in me.\nThe life I live in the body\nI live by faith\nin the Son of God\nwho loved me\nand gave himself for me.\n\nGalatians 2:20",
  "But the fruit of the Spirit\nis love, joy, peace,\npatience, kindness,\ngoodness, faithfulness\ngentleness and self-control.\nAgainst such things\nthere is no law.\n\nGalatians 5:22-23",
  "Do not be deceived\nGod cannot be mocked.\nA man reaps\nwhat he sows.\n\nGalatians 6:7",
  "In whom we have redemption through his blood,\nthe forgiveness of sins,\naccording to the riches of his grace\n\nEphesians 1:7",
  "Let no corrupt communication\nproceed out of your mouth,\nbut that which is good\nto the use of edifying,\nthat it may minister grace\nunto the hearers.\n\nEphesians 4:29",
  "And be ye kind one to another,\ntenderhearted, forgiving one another,\neven as God for Christ's sake\nhath forgiven you.\n\nEphesians 4:32",
  'Children,\nobey your parents in the Lord for this is right.\nHonour thy father and mother\nwhich is the first commandment with promise\nThat it may be well with thee,\nand thou mayest live long on the earth.\n\nEphesians 6:1-3',
  "For to me\nto live is Christ\nand to die is gain.\n\nPhilippians 1:21",
  "But our citizenship is in heaven.\nAnd we eagerly await\na Savior from there\nthe Lord Jesus Christ\n\nPhilippians 3:20",
  "Devote\nyourselves to prayer\nbeing watchful\nand thankful.\n\nColossians 4:2",
  "Be joyful always\npray continually\ngive thanks in all circumstances\nfor this is God's will for you\nin Christ Jesus.\n\n1 Thessalonians 5:16-18",
  "For there is one God\nand one mediator\nbetween God and men\nthe man Christ Jesus\n\n1 Timothy 2:5",
  "If anyone does not provide\nfor his relatives\nand especially for his immediate family\nhe has denied the faith\nand is worse\nthan an unbeliever.\n\n1 Timothy 5:8",
  "What you heard from me\nkeep as the pattern\nof sound teaching\nwith faith and love\nin Christ Jesus.\n\n2 Timothy 1:13",
  "Guard the good deposit\nthat was entrusted to you--guard\nit with the help\nof the Holy Spirit\nwho lives in us.\n\n2 Timothy 1:14",
  "Do your best to present\nyourself to God\nas one approved a workman\nwho does not need to be ashamed\nand who correctly handles\nthe word of truth.\n\n2 Timothy 2:15",
  "Nevertheless\nGod's solid foundation stands firm\nsealed with this inscription\nThe Lord knows those\nwho are his\nand Everyone who confesses\nthe name of the Lord\nmust turn away\nfrom wickedness.\n\n2 Timothy 2:19",
  "In fact\neveryone who wants to live\na godly life\nin Christ Jesus\nwill be persecuted\n\n2 Timothy 3:12",
  "he saved us\nnot because of righteous things\nwe had done\nbut because of his mercy.\nHe saved us\nthrough the washing of rebirth\nand renewal by\nthe Holy Spirit\n\nTitus 3:5",
  "Because he himself suffered\nwhen he was tempted\nhe is able to help those\nwho are being tempted.\n\nHebrews 2:18",
  "Let us then approach\nthe throne of grace\nwith confidence\nso that we may receive mercy\nand find grace to help us\nin our time of need.\n\nHebrews 4:16",
  "Therefore he is able to save\ncompletely those who come to God\nthrough him\nbecause he always lives\nto intercede for them.\n\nHebrews 7:25",
  "And without faith\nit is impossible to please God\nbecause anyone who comes to him\nmust believe that he exists\nand that he rewards those\nwho earnestly seek him.\n\nHebrews 11:6",
  "Consider him who endured\nsuch opposition from sinful men\nso that you will not grow\nweary and lose heart.\n\nHebrews 12:3",
  'Keep your lives free\nfrom the love of money\nand be content with\nwhat you have\nbecause God has said\nNever will I leave you\nnever will I forsake you.\n\nHebrews 13:5',
  "Blessed is the man\nwho perseveres under trial\nbecause when he has stood the test\nhe will receive\nthe crown of life\nthat God has promised to\nthose who love him.\n\nJames 1:12",
  "Do not merely listen to the word\nand so deceive yourselves.\nDo what it says.\n\nJames 1:22",
  "If anyone considers\nhimself religious\nand yet does not keep\na tight rein on his tongue\nhe deceives himself\nand his religion is worthless.\n\nJames 1:26",
  "For whoever keeps the whole law\nand yet stumbles\nat just one point\nis guilty of breaking\nall of it.\n\nJames 2:10",
  "As the body without\nthe spirit is dead\nso faith without\ndeeds is dead.\n\nJames 2:26",
  "Anyone, then\nwho knows the good\nhe ought to do\nand doesn't do it\nsins.\n\nJames 4:17",
  "Like newborn babies\ncrave pure spiritual milk\nso that by it\nyou may grow up\nin your salvation\n\n1 Peter 2:2",
  "For Christ died for sins\nonce for all\nthe righteous for the unrighteous\nto bring you to God.\nHe was put to death in the body\nbut made alive by the Spirit\n\n1 Peter 3:18",
  "If we confess our sins,\nhe is faithful and just\nand will forgive us our sins\nand purify us\nfrom all unrighteousness.\n\n1 John 1:9",
  "Do not be surprised,\nmy brothers,\nif the world hates you.\n\n1 John 3:13",
  "Dear children,\nlet us not love\nwith words or tongue\nbut with actions\nand in truth.\n\n1 John 3:18",
  "The LORD is a refuge\nfor the oppressed\na stronghold in times\nof trouble.\n\nPsalm 9:9",
  "The lions may grow\nweak and hungry,\nbut those who seek the LORD\nlack no good thing.\n\nPsalm 34:10",
  "Trust in the LORD forever\nfor the LORD, the LORD\nis the Rock eternal.\n\nIsaiah 26:4",
  "You are my hiding place\nyou will protect me\nfrom trouble\nand surround me\nwith songs of deliverance.\n\nPsalm 32:7",
  "The LORD replied\nMy Presence will go with you\nand I will give you rest.\n\nExodus 33:14",
  "And the LORD,\nhe it is that doth go before thee\nhe will be with thee,\nhe will not fail thee,\nneither forsake thee\nfear not,\nneither be dismayed.\n\nDeuteronomy 31:8",
  "The eternal God is thy refuge,\nand underneath are the everlasting arms\nand he shall thrust out\nthe enemy from before thee\nand shall say, Destroy them.\n\nDeuteronomy 33:27",
  "The righteous cry out,\nand the LORD hears them\nhe delivers them\nfrom all their troubles.\n\nPsalm 34:17",
  "In repentance and rest\nis your salvation\nin quietness and trust\nis your strength\nbut you would have none of it.\n\nIsaiah 30:15",
  "Who of you\nby worrying can\nadd a single hour to his life?\nSince you cannot do\nthis very little thing\nwhy do you worry\nabout the rest?\n\nLuke 12:25-26",
  "Peace I leave with you,\nmy peace I give unto you not as the world giveth,\ngive I unto you.\nLet not your heart be troubled,\nneither let it be afraid.\n\nJohn 14:27",
  "I sought the LORD,\nand he answered me\nhe delivered me\nfrom all my fears.\n\nPsalm 34:4",
  "Have I not commanded you?\nBe strong and courageous.\nDo not be terrified\ndo not be discouraged\nfor the LORD your God\nwill be with you\nwherever you go.\n\nJoshua 1:9",
  "The LORD is near\nto all who call on him,\nto all who call\non him in truth.\nHe fulfills the desires of those\nwho fear him\nhe hears their cry\nand saves them.\n\nPsalm 145:18-19",
  "For God did not give us\na spirit of timidity\nbut a spirit of power\nof love\nand of self-discipline.\n\n2 Timothy 1:7",
  "When I called,\nyou answered me\nyou made me bold\nand stouthearted.\n\nPsalm 138:3",
  "My soul finds rest in God alone\nmy salvation comes from him.\nHe alone is my rock\nand my salvation\nhe is my fortress,\nI will never be shaken.\n\nPsalm 62:1-2",
  "Praise the LORD.\nBlessed is the man\nwho fears the LORD,\nwho finds great delight\nin his commands.\n\nPsalm 112:1",
  "I will say of the LORD\nHe is my refuge\nand my fortress\nmy God in whom I trust.\n\nPsalm 91:2",
  "My grace is sufficient\nfor you\nfor my power\nis made perfect\nin weakness.\n\n2 Corinthians 12:9",
  "But the Lord is faithful\nand he will strengthen\nand protect you\nfrom the evil one.\n\n2 Thessalonians 3:3",
  "He gives strength\nto the weary\nand increases the power\nof the weak.\n\nIsaiah 40:29",
  "And the God of all grace\nwho called you\nto his eternal glory in Christ\nafter you have suffered\na little while\nwill himself restore you\nand make you strong\nfirm and steadfast.\n\n1 Peter 5:10",
  "Now may the Lord of peace himself\ngive you peace at all times\nand in every way.\nThe Lord be with\nall of you.\n\n2 Thessalonians 3:16",
];
List<String> _koreanVerse = [
  '이를 위하여\n죽은 자들에게도\n복음이 전파되었으니\n이는 육체로는\n사람으로 심판을 받으나\n영으로는 하나님을 따라\n살게 하려 함이라\n\n베드로전서 4장 6절',
  "이것들이 아침마다 새로우니\n주의 성실하심이 크시도소이다\n내 심령에 이르기를\n여호와는 나의 기업이시니\n그러므로 내가 그를 바라리라 하도다\n\n예레미야애가 3:22-23",
  "사람이 친구를 위하여\n자기 목숨을 버리면\n이보다 더 큰 사랑이 없나니\n\n요한복음 15:13",
  "우리 가운데서\n역사하시는 능력대로\n우리가 구하거나\n생각하는 모든 것에 더 넘치도록\n능히 하실 이에게\n\n에베소서 3:20",
  "너희는 강하고 담대하라 두려워하지 말라\n그들 앞에서 떨지 말라\n이는 네 하나님 여호와 그가 너와 함께 가시며\n결코 너를 떠나지 아니하시며\n버리지 아니하실 것임이라 하고\n\n신명기 31:6",
  "여호와는 나의 빛이요\n나의 구원이시니\n내가 누구를 두려워하리요\n여호와는 내 생명의 능력이시니\n내가 누구를 무서워하리요\n\n시편 27:1",
  "사랑 안에 두려움이 없고\n온전한 사랑이\n두려움을 내쫓나니\n두려움에는 형벌이 있음이라\n두려워하는 자는 사랑 안에서\n온전히 이루지 못하였느니라\n\n요한1서 4:18",
  "그런즉 이 일에 대하여\n우리가 무슨 말 하리요\n만일 하나님이 우리를 위하시면\n누가 우리를 대적하리요\n\n로마서 8:31",
  "소망의 하나님이\n모든 기쁨과 평강을 믿음 안에서\n너희에게 충만하게 하사\n성령의 능력으로\n소망이 넘치게 하시기를 원하노라\n\n로마서 15:13",
  "여호와를\n바라는 너희들아\n강하고 담대하라\n\n시편 31:24",
  "두려워하지 말라\n내가 너와 함께 함이라\n놀라지 말라 나는 네 하나님이 됨이라\n내가 너를 굳세게 하리라\n참으로 너를 도와 주리라\n참으로 나의 의로운 오른손으로\n너를 붙들리라\n\n이사야 41:10",
  "오직 여호와를 앙망하는 자는\n새 힘을 얻으리니\n독수리가 날개치며 올라감 같을 것이요\n달음박질하여도 곤비하지 아니하겠고\n걸어가도 피곤하지 아니하리로다\n\n이사야 40:31",
  "예수께서 그들을 보시며 이르시되\n사람으로는 할 수 없으되\n하나님으로는 그렇지 아니하니\n하나님으로서는 다 하실 수 있느니라\n\n마가복음 10:27",
  "너희 염려를\n다 주께 맡기라\n이는 그가 너희를\n돌보심이라\n\n베드로전서 5:7",
  "예수께서\n그들을 보시며 이르시되\n사람으로는 할 수 없으나\n하나님으로서는 다 하실 수 있느니라\n\n마태복음 19:26",
  "내게 능력 주시는 자 안에서\n내가 모든 것을\n할 수 있느니라\n\n빌립보서 4:13",
  "그러므로 내 사랑하는 형제들아\n견실하며 흔들리지 말고\n항상 주의 일에 더욱 힘쓰는 자들이 되라\n이는 너희 수고가\n주 안에서 헛되지 않은 줄 앎이라\n\n고린도전서 15:58",
  "너희 모든 일을\n사랑으로 행하라\n\n고린도전서 16:14",
  "이르시되\n너희 믿음이 작은 까닭이니라\n진실로 너희에게 이르노니\n만일 너희에게 믿음이\n겨자씨 한 알 만큼만 있어도\n이 산을 명하여\n여기서 저기로 옮겨지라 하면 옮겨질 것이요\n또 너희가 못할 것이 없으리라\n\n마태복음 17:20",
  "여호와께 감사하라\n그는 선하시며\n그 인자하심이 영원함이로다\n\n시편 107:1",
  '여호와의 말씀이니라\n너희를 향한 나의 생각을 내가 아나니\n평안이요 재앙이 아니니라\n너희에게 미래와 희망을 주는 것이니라\n\n예레미야 29:11',
  "너희는\n여호와의 선하심을 맛보아 알지어다\n그에게 피하는 자는\n복이 있도다\n\n시편 34:8",
  "우리가 알거니와\n하나님을 사랑하는 자\n곧 그의 뜻대로 부르심을 입은 자들에게는\n모든 것이 합력하여\n선을 이루느니라\n\n로마서 8:28",
  "너는 마음을 다하여\n여호와를 신뢰하고\n네 명철을 의지하지 말라\n\n잠언 3:5-6",
  "여호와의 이름은 견고한 망대라\n의인은 그리로 달려가서\n안전함을 얻느니라\n\n잠언 18:10",
  "내가 여호와를\n항상 내 앞에 모심이여\n그가 나의 오른쪽에 계시므로\n내가 흔들리지 아니하리로다\n\n시편 16:8",
  "내가 사망의 음침한\n골짜기로 다닐지라도\n해를 두려워하지 않을 것은\n주께서 나와 함께 하심이라\n주의 지팡이와 막대기가\n나를 안위하시나이다\n\n시편 23:4",
  "만군의 여호와께서\n우리와 함께 하시니\n야곱의 하나님은\n우리의 피난처시로다\n\n시편 46:7",
  "네 짐을 여호와께 맡기라\n그가 너를 붙드시고\n의인의 요동함을\n영원히 허락하지 아니하시리로다\n\n시편 55:22",
  "오직 그만이 나의 반석이시요\n나의 구원이시요\n나의 요새이시니\n내가 흔들리지 아니하리로다\n\n시편 62:6",
  "주는 나의 은신처요 방패시라\n내가 주의 말씀을 바라나이다\n너희 행악자들이여 나를 떠날지어다\n나는 내 하나님의 계명들을\n지키리로다\n\n시편 119:114-115",
  "이 말씀은\n나의 고난 중의 위로라\n주의 말씀이\n나를 살리셨기 때문이니이다\n\n시편 119:50",
  "내가 환난 중에\n여호와께 부르짖었더니\n내게 응답하셨도다\n\n시편 120:1",
  "주께서 심지가 견고한 자를\n평강하고 평강하도록 지키시리니\n이는 그가 주를 신뢰함이니이다\n\n이사야 26:3",
  "수고하고 무거운 짐 진 자들아\n다 내게로 오라\n내가 너희를 쉬게 하리라\n\n마태복음 11:28",
  "이것을 너희에게 이르는 것은\n너희로 내 안에서\n평안을 누리게 하려 함이라\n세상에서는 너희가 환난을 당하나\n담대하라 내가 세상을 이기었노라\n\n요한복음 16:33",
  "그러므로 피차 권면하고\n서로 덕을 세우기를\n너희가 하는 것 같이 하라\n\n데살로니가전서 5:11",
  "나의 하나님이\n그리스도 예수 안에서\n영광 가운데\n그 풍성한 대로\n너희 모든 쓸 것을\n채우시리라\n\n빌립보서 4:19",
  "여호와는 선하시며\n환난 날에 산성이시라\n그는 자기에게 피하는 자들을 아시느니라\n\n나훔 1:7",
  "내가 여호와께 바라는 한 가지 일\n그것을 구하리니\n곧 내가 내 평생에 여호와의 집에 살면서\n여호와의 아름다움을 바라보며\n그의 성전에서 사모하는 그것이라\n\n시편 27:4",
  "친구는 사랑이\n끊어지지 아니하고\n형제는 위급한 때를 위하여\n났느니라\n\n잠언 17:17",
  "우리가 지금은\n거울로 보는 것 같이 희미하나\n그 때에는 얼굴과 얼굴을 대하여 볼 것이요\n지금은 내가 부분적으로 아나\n그 때에는 주께서 나를 아신 것 같이\n내가 온전히 알리라\n\n고린도전서 13:12",
  "깨어\n믿음에 굳게 서서\n남자답게 강건하라\n\n고린도전서 16:13",
  "사랑하는 자들아\n거류민과 나그네 같은 너희를 권하노니\n영혼을 거슬러\n싸우는 육체의 정욕을 제어하라\n\n베드로전서 2:11",
  "무엇이든지 구하는 바를\n그에게서 받나니\n이는 우리가 그의 계명을 지키고\n그 앞에서 기뻐하시는 것을 행함이라\n\n요한1서 3:22",
  "여호와는 나의 힘이요\n노래시며 나의 구원이시로다\n그는 나의 하나님이시니\n내가 그를 찬송할 것이요\n내 아버지의 하나님이시니\n내가 그를 높이리로다\n\n출애굽기 15:2",
  "부와 귀가 주께로 말미암고\n또 주는 만물의 주재가 되사\n손에 권세와 능력이 있사오니\n모든 사람을 크게 하심과\n강하게 하심이\n주의 손에 있나이다\n\n역대상 29:12",
  "너의 하나님 여호와가\n너의 가운데에 계시니\n그는 구원을 베푸실 전능자이시라\n그가 너로 말미암아\n기쁨을 이기지 못하시며\n너를 잠잠히 사랑하시며\n너로 말미암아\n즐거이 부르며\n기뻐하시리라 하리라\n\n스바냐 3:17",
  "주의 대적으로 말미암아\n어린 아이들과 젖먹이들의 입으로\n권능을 세우심이여\n이는 원수들과 보복자들을\n잠잠하게 하려 하심이니이다\n\n시편 8:2",
  "나의 힘이신 여호와여\n내가 주를 사랑하나이다\n여호와는 나의 반석이시요 나의 요새시요\n나를 건지시는 이시요\n나의 하나님이시요\n내가 그 안에 피할 나의 바위시요\n나의 방패시요\n나의 구원의 뿔이시요 나의 산성이시로다\n\n시편 18:1-2",
  "의인들의 구원은\n여호와로부터 오나니\n그는 환난 때에\n그들의 요새이시로다\n\n시편 37:39",
  "내가 주 여호와의\n능하신 행적을\n가지고 오겠사오며\n주의 공의만 전하겠나이다\n\n시편 71:16",
  "나의 영혼이 눌림으로 말미암아\n녹사오니 주의 말씀대로\n나를 세우소서\n\n시편 119:28",
  "보라 하나님은 나의 구원이시라\n내가 신뢰하고 두려움이 없으리니\n주 여호와는 나의 힘이시며\n나의 노래시며 나의 구원이심이라\n\n이사야 12:2",
  "주 여호와는 나의 힘이시라\n나의 발을 사슴과 같게 하사\n나를 나의 높은 곳으로 다니게 하시리로다\n이 노래는 지휘하는 사람을 위하여\n내 수금에 맞춘 것이니라\n\n하박국 3:19",
  "그러므로 내일 일을 위하여\n염려하지 말라\n내일 일은 내일이 염려할 것이요\n한 날의 괴로움은\n그 날로 족하니라\n\n마태복음 6:34",
  "네 마음을 다하고\n목숨을 다하고\n뜻을 다하고\n힘을 다하여\n주 너의 하나님을 사랑하라 하신 것이요\n\n마가복음 12:30",
  "오직 성령이 너희에게 임하시면\n너희가 권능을 받고\n예루살렘과 온 유대와 사마리아와\n땅 끝까지 이르러\n내 증인이 되리라 하시니라\n\n사도행전 1:8",
  "그러므로 우리가\n낙심하지 아니하노니\n우리의 겉사람은 낡아지나\n우리의 속사람은 날로 새로워지도다\n\n고린도후서 4:16",
  "그의 영광의 풍성함을 따라\n그의 성령으로 말미암아\n너희 속사람을 능력으로\n강건하게 하시오며\n\n에베소서 3:16",
  "끝으로 너희가\n주 안에서와\n그 힘의 능력으로\n강건하여지고\n\n에베소서 6:10",
  "너희 안에서\n착한 일을 시작하신 이가\n그리스도 예수의 날까지\n이루실 줄을 우리는 확신하노라\n\n빌립보서 1:6",
  "여호와께서 사람의 걸음을 정하시고\n그의 길을 기뻐하시나니\n그는 넘어지나 아주 엎드러지지 아니함은\n여호와께서 그의 손으로 붙드심이로다\n\n시편 37:23-24",
  "적은 무리여\n무서워 말라\n너희 아버지께서 그 나라를\n너희에게 주시기를\n기뻐하시느니라\n\n누가복음 12:32",
  "그리하면\n모든 지각에 뛰어난 하나님의 평강이\n그리스도 예수 안에서\n너희 마음과 생각을 지키시리라\n\n빌립보서 4:7",
  "이는 우리가 믿음으로 행하고\n보는 것으로\n행하지 아니함이로라\n\n고린도후서 5:7",
  "믿음의 선한 싸움을 싸우라\n영생을 취하라\n이를 위하여 네가 부르심을 받았고\n많은 증인 앞에서\n선한 증언을 하였도다\n\n디모데전서 6:12",
  "자녀들아 너희는 하나님께 속하였고\n또 그들을 이기었나니\n이는 너희 안에 계신 이가\n세상에 있는 자보다 크심이라\n\n요한1서 4:4",
  "여호와를 찬송함이여\n내 간구하는 소리를 들으심이로다\n여호와는 나의 힘과 나의 방패이시니\n내 마음이 그를 의지하여 도움을 얻었도다\n그러므로 내 마음이 크게 기뻐하며\n내 노래로 그를 찬송하리로다\n\n시편 28:6-7",
  "여호와와\n그의 능력을 구할지어다\n항상 그의 얼굴을 찾을지어다\n\n역대상 16:11",
  "주께서 내 곁에 서서\n나에게 힘을 주심은\n나로 말미암아 선포된 말씀이\n온전히 전파되어\n모든 이방인이 듣게 하려 하심이니\n내가 사자의 입에서 건짐을 받았느니라\n\n디모데후서 4:17",
  "여호와는 나의 능력과\n찬송이시요\n또 나의 구원이 되셨도다\n\n시편 118:14",
  "믿음은\n바라는 것들의 실상이요\n보이지 않는 것들의 증거니\n\n히브리서 11:1",
  "우리가 이 소망을 가지고 있는 것은\n영혼의 닻 같아서\n튼튼하고 견고하여\n휘장 안에 들어 가나니\n\n히브리서 6:19",
  "또 약속하신 이는 미쁘시니\n우리가 믿는 도리의 소망을\n움직이지 말며\n굳게 잡고\n\n히브리서 10:23",
  "그러므로\n내가 그리스도를 위하여\n약한 것들과 능욕과 궁핍과\n박해와 곤고를 기뻐하노니\n이는 내가 약한 그 때에 강함이라\n\n고린도후서 12:10",
  "대저 하나님의 모든 말씀은\n능하지 못하심이\n없느니라\n\n누가복음 1:37",
  "이는 당신이 주장할 일이니\n일어나소서 우리가 도우리니\n힘써 행하소서 하니라\n\n에스라 10:4",
  "태초에\n하나님이\n천지를\n창조하시니라\n\n창세기 1:1",
  "너희는 도둑질하지 말며\n속이지 말며\n서로 거짓말하지 말며\n\n레위기 19:11",
  '하나님은 사람이 아니시니\n거짓말을 하지 않으시고\n인생이 아니시니\n후회가 없으시도다\n어찌 그 말씀하신 바를\n행하지 않으시며\n하신 말씀을 실행하지 않으시랴\n\n민수기 23:19',
  "내가 두려워하는 날에는\n내가 주를\n의지하리이다\n\n시편 56:3",
  "여호와께 노래하여\n그의 이름을 송축하며\n그의 구원을\n날마다 전파할지어다\n\n시편 96:2",
  "청년이 무엇으로\n그의 행실을 깨끗하게 하리이까\n주의 말씀만\n지킬 따름이니이다\n\n시편 119:9",
  "내가 주께\n범죄하지 아니하려 하여\n주의 말씀을\n내 마음에 두었나이다\n\n시편 119:11",
  "우리 주는 위대하시며\n능력이 많으시며\n그의 지혜가 무궁하시도다\n\n시편 147:5",
  "네 재물과 네 소산물의\n처음 익은 열매로\n여호와를 공경하라\n그리하면 네 창고가 가득히 차고\n네 포도즙 틀에\n새 포도즙이 넘치리라\n\n잠언 3:9-10",
  "우리는 다 양 같아서\n그릇 행하여 각기 제 길로 갔거늘\n여호와께서는 우리 모두의 죄악을\n그에게 담당시키셨도다\n\n이사야 53:6",
  '아들을 낳으리니\n이름을 예수라 하라\n이는 그가 자기 백성을\n그들의 죄에서\n구원할 자이심이라 하니라\n\n마태복음 1:21',
  '말씀하시되\n나를 따라오라\n내가 너희를\n사람을 낚는 어부가 되게 하리라 하시니\n\n마태복음 4:19',
  '이같이 너희 빛이\n사람 앞에 비치게 하여\n그들로 너희 착한 행실을 보고\n하늘에 계신 너희 아버지께\n영광을 돌리게 하라\n\n마태복음 5:16',
  '나와 함께 아니하는 자는\n나를 반대하는 자요\n나와 함께 모으지 아니하는 자는\n헤치는 자니라\n\n마태복음 12:30',
  '두세 사람이\n내 이름으로 모인 곳에는\n나도 그들 중에 있느니라\n\n마태복음 18:20',
  '인자가 온 것은\n섬김을 받으려 함이 아니라\n도리어 섬기려 하고\n자기 목숨을 많은 사람의 대속물로\n주려 함이니라\n\n마가복음 10:45',
  '그러나 그 날과 그 때는 아무도 모르나니\n하늘에 있는 천사들도,\n아들도 모르고 아버지만 아시느니라\n주의하라 깨어 있으라\n그 때가 언제인지 알지 못함이라\n\n마가복음 13:32-33',
  '또 이르시되\n너희는 온 천하에 다니며\n만민에게 복음을 전파하라\n\n마가복음 16:15',
  '또 무리에게 이르시되\n아무든지 나를 따라오려거든\n자기를 부인하고\n날마다 제 십자가를 지고\n나를 따를 것이니라\n\n누가복음 9:23',
  '예수께서 이르시되\n오히려 하나님의 말씀을\n듣고 지키는 자가\n복이 있느니라 하시니라\n\n누가복음 11:28',
  '지극히 작은 것에 충성된 자는\n큰 것에도 충성되고\n지극히 작은 것에 불의한 자는\n큰 것에도 불의하니라\n\n누가복음 16:10',
  '집 하인이 두 주인을 섬길 수 없나니\n혹 이를 미워하고 저를 사랑하거나\n혹 이를 중히 여기고\n저를 경히 여길 것임이니라\n너희는 하나님과 재물을\n겸하여 섬길 수 없느니라\n\n누가복음 16:13',
  "영접하는 자\n곧 그 이름을 믿는 자들에게는\n하나님의 자녀가 되는 권세를 주셨으니\n\n요한복음 1:12",
  '아들을 믿는 자에게는 영생이 있고\n아들에게 순종하지 아니하는 자는\n영생을 보지 못하고\n도리어 하나님의 진노가\n그 위에 머물러 있느니라\n\n요한복음 3:36',
  '내가 진실로 진실로 너희에게 이르노니\n내 말을 듣고 또 나 보내신 이를 믿는 자는\n영생을 얻었고 심판에 이르지 아니하나니\n사망에서 생명으로 옮겼느니라\n\n요한복음 5:24',
  '새 계명을 너희에게 주노니\n서로 사랑하라\n내가 너희를 사랑한 것 같이 너희도 서로 사랑하라\n너희가 서로 사랑하면\n이로써 모든 사람이 너희가 내 제자인 줄 알리라\n\n요한복음 13:34-35',
  '예수께서 이르시되\n내가 곧 길이요 진리요 생명이니\n나로 말미암지 않고는\n아버지께로 올 자가 없느니라\n\n요한복음 14:6',
  '나의 계명을 지키는 자라야\n나를 사랑하는 자니\n나를 사랑하는 자는 내 아버지께 사랑을 받을 것이요\n나도 그를 사랑하여\n그에게 나를 나타내리라\n\n요한복음 14:21',
  '너희가 내 안에 거하고\n내 말이 너희 안에 거하면\n무엇이든지 원하는 대로 구하라\n그리하면 이루리라\n\n요한복음 15:7',
  '그들을 진리로\n거룩하게 하옵소서\n아버지의 말씀은 진리니이다\n\n요한복음 17:17',
  "오직 이것을 기록함은\n너희로 예수께서 하나님의 아들\n그리스도이심을 믿게 하려 함이요\n또 너희로 믿고 그 이름을 힘입어\n생명을 얻게 하려 함이니라\n\n요한복음 20:31",
  '다른 이로써는 구원을 받을 수 없나니\n천하 사람 중에\n구원을 받을 만한 다른 이름을\n우리에게 주신 일이\n없음이라 하였더라\n\n사도행전 4:12',
  '이것으로 말미암아\n나도 하나님과 사람에 대하여\n항상 양심에 거리낌이 없기를\n힘쓰나이다\n\n사도행전 24:16',
  "내가 복음을 부끄러워하지 아니하노니\n이 복음은 모든 믿는 자에게\n구원을 주시는 하나님의 능력이 됨이라\n먼저는 유대인에게요\n그리고 헬라인에게로다\n\n로마서 1:16",
  "모든 사람이\n죄를 범하였으매\n하나님의 영광에 이르지 못하더니\n\n로마서 3:23",
  "약속하신 그것을\n또한 능히 이루실 줄을\n확신하였으니\n\n로마서 4:21",
  "그러므로 우리가 믿음으로\n의롭다 하심을 받았으니\n우리 주 예수 그리스도로 말미암아\n하나님과 화평을 누리자\n\n로마서 5:1",
  "우리가 아직 죄인 되었을 때에\n그리스도께서 우리를 위하여 죽으심으로\n하나님께서 우리에 대한\n자기의 사랑을 확증하셨느니라\n\n로마서 5:8",
  "그러므로 한 사람으로 말미암아\n죄가 세상에 들어오고\n죄로 말미암아 사망이 들어왔나니\n이와 같이 모든 사람이\n죄를 지었으므로\n사망이 모든 사람에게 이르렀느니라\n\n로마서 5:12",
  "그런즉\n우리가 무슨 말을 하리요\n은혜를 더하게 하려고\n죄에 거하겠느냐\n\n로마서 6:1-2",
  "죄가 너희를 주장하지 못하리니\n이는 너희가 법 아래에 있지 아니하고\n은혜 아래에 있음이라\n\n로마서 6:14",
  "죄의 삯은 사망이요\n하나님의 은사는\n그리스도 예수 우리 주 안에 있는\n영생이니라\n\n로마서 6:23",
  "그러므로\n이제 그리스도 예수\n안에 있는 자에게는\n결코 정죄함이 없나니\n\n로마서 8:1",
  "자기 아들을 아끼지 아니하시고\n우리 모든 사람을 위하여\n내주신 이가 어찌 그 아들과 함께\n모든 것을 우리에게\n주시지 아니하겠느냐\n\n로마서 8:32",
  '누구든지\n주의 이름을 부르는 자는\n구원을 받으리라\n\n로마서 10:13',
  "그러므로\n믿음은 들음에서 나며\n들음은 그리스도의 말씀으로\n말미암았느니라\n\n로마서 10:17",
  "만일 은혜로 된 것이면\n행위로 말미암지 않음이니\n그렇지 않으면\n은혜가 은혜 되지 못하느니라\n\n로마서 11:6",
  "아무에게도\n악을 악으로 갚지 말고\n모든 사람 앞에서\n선한 일을 도모하라\n\n로마서 12:17",
  "할 수 있거든\n너희로서는\n모든 사람과 더불어\n화목하라\n\n로마서 12:18",
  "각 사람은 위에 있는 권세들에게 복종하라\n권세는 하나님으로부터 나지 않음이 없나니\n모든 권세는\n다 하나님께서 정하신 바라\n\n로마서 13:1",
  "그러므로\n그리스도께서 우리를 받아\n하나님께 영광을 돌리심과 같이\n너희도 서로 받으라\n\n로마서 15:7",
  "십자가의 도가\n멸망하는 자들에게는\n미련한 것이요\n구원을 받는 우리에게는\n하나님의 능력이라\n\n고린도전서 1:18",
  '기록된 바\n자랑하는 자는\n주 안에서 자랑하라 함과\n같게 하려 함이라\n\n고린도전서 1:31',
  "우리가 세상의 영을 받지 아니하고\n오직 하나님으로부터 온 영을 받았으니\n이는 우리로 하여금\n하나님께서 우리에게 은혜로 주신 것들을\n알게 하려 하심이라\n\n고린도전서 2:12",
  "너희는 너희가 하나님의 성전인 것과\n하나님의 성령이\n너희 안에 계시는 것을\n알지 못하느냐\n\n고린도전서 3:16",
  "값으로 산 것이 되었으니\n그런즉 너희 몸으로\n하나님께 영광을 돌리라\n\n고린도전서 6:20",
  '속지 말라\n악한 동무들은\n선한 행실을 더럽히나니\n\n고린도전서 15:33',
  "우리는 우리를 전파하는 것이 아니라\n오직 그리스도 예수의 주 되신 것과\n또 예수를 위하여\n우리가 너희의 종 된 것을\n전파함이라\n\n고린도후서 4:5",
  "그런즉 누구든지\n그리스도 안에 있으면\n새로운 피조물이라\n이전 것은 지나갔으니\n보라 새 것이 되었도다\n\n고린도후서 5:17",
  "너희는 믿지 않는 자와\n멍에를 함께 메지 말라\n의와 불법이 어찌 함께 하며\n빛과 어둠이 어찌 사귀며\n\n고린도후서 6:14",
  "너희는 믿음 안에 있는가\n너희 자신을 시험하고 너희 자신을 확증하라\n예수 그리스도께서 너희 안에 계신 줄을\n너희가 스스로 알지 못하느냐\n그렇지 않으면 너희는 버림 받은 자니라\n\n고린도후서 13:5",
  "내가 그리스도와 함께\n십자가에 못 박혔나니\n그런즉 이제는 내가 사는 것이 아니요\n오직 내 안에 그리스도께서\n사시는 것이라\n이제 내가 육체 가운데 사는 것은\n나를 사랑하사\n나를 위하여 자기 자신을 버리신\n하나님의 아들을 믿는\n믿음 안에서 사는 것이라\n\n갈라디아서 2:20",
  "오직 성령의 열매는\n사랑과 희락과 화평과\n오래 참음과 자비와 양선과 충성과\n온유와 절제니\n이같은 것을 금지할 법이 없느니라\n\n갈라디아서 5:22-23",
  "스스로 속이지 말라\n하나님은 업신여김을\n받지 아니하시나니\n사람이 무엇으로 심든지\n그대로 거두리라\n\n갈라디아서 6:7",
  "우리는 그리스도 안에서\n그의 은혜의 풍성함을 따라\n그의 피로 말미암아\n속량 곧 죄 사함을 받았느니라\n\n에베소서 1:7",
  "무릇 더러운 말은\n너희 입 밖에도 내지 말고\n오직 덕을 세우는 데 소용되는 대로\n선한 말을 하여\n듣는 자들에게 은혜를 끼치게 하라\n\n에베소서 4:29",
  "서로 친절하게 하며\n불쌍히 여기며 서로 용서하기를\n하나님이 그리스도 안에서\n너희를 용서하심과 같이 하라\n\n에베소서 4:32",
  '자녀들아 주 안에서\n너희 부모에게 순종하라 이것이 옳으니라\n네 아버지와 어머니를 공경하라\n이것은 약속이 있는 첫 계명이니\n이로써 네가 잘되고 땅에서 장수하리라\n\n에베소서 6:1-3',
  "이는 내게 사는 것이\n그리스도니\n죽는 것도 유익함이라\n\n빌립보서 1:21",
  "그러나 우리의 시민권은\n하늘에 있는지라\n거기로부터 구원하는 자\n곧 주 예수 그리스도를\n기다리노니\n\n빌립보서 3:20",
  "기도를 계속하고\n기도에 감사함으로\n깨어 있으라\n\n골로새서 4:2",
  "항상 기뻐하라\n쉬지 말고 기도하라\n범사에 감사하라\n이것이 그리스도 예수 안에서\n너희를 향하신 하나님의 뜻이니라\n\n데살로니가전서 5:16-18",
  "하나님은 한 분이시요\n또 하나님과 사람 사이에\n중보자도 한 분이시니\n곧 사람이신 그리스도 예수라\n\n디모데전서 2:5",
  "누구든지\n자기 친족 특히 자기 가족을\n돌보지 아니하면\n믿음을 배반한 자요\n불신자보다 더 악한 자니라\n\n디모데전서 5:8",
  "너는 그리스도 예수 안에 있는\n믿음과 사랑으로써\n내게 들은 바\n바른 말을 본받아 지키고\n\n디모데후서 1:13",
  "우리 안에\n거하시는 성령으로 말미암아\n네게 부탁한\n아름다운 것을 지키라\n\n디모데후서 1:14",
  "너는 진리의 말씀을 옳게 분별하며\n부끄러울 것이 없는 일꾼으로\n인정된 자로 자신을 하나님 앞에\n드리기를 힘쓰라\n\n디모데후서 2:15",
  "그러나 하나님의 견고한 터는 섰으니\n인침이 있어 일렀으되\n주께서 자기 백성을 아신다 하며\n또 주의 이름을 부르는 자마다\n불의에서 떠날지어다 하였느니라\n\n디모데후서 2:19",
  "무릇 그리스도 예수 안에서\n경건하게 살고자 하는 자는\n박해를 받으리라\n\n디모데후서 3:12",
  "우리를 구원하시되\n우리가 행한 바\n의로운 행위로 말미암지 아니하고\n오직 그의 긍휼하심을 따라\n중생의 씻음과\n성령의 새롭게 하심으로 하셨나니\n\n디도서 3:5",
  "그가 시험을 받아\n고난을 당하셨은즉\n시험 받는 자들을\n능히 도우실 수 있느니라\n\n히브리서 2:18",
  "그러므로\n우리는 긍휼하심을 받고\n때를 따라 돕는 은혜를\n얻기 위하여\n은혜의 보좌 앞에\n담대히 나아갈 것이니라\n\n히브리서 4:16",
  "그러므로 자기를 힘입어\n하나님께 나아가는 자들을\n온전히 구원하실 수 있으니\n이는 그가 항상 살아 계셔서\n그들을 위하여 간구하심이라\n\n히브리서 7:25",
  "믿음이 없이는 하나님을 기쁘시게 하지 못하나니\n하나님께 나아가는 자는\n반드시 그가 계신 것과\n또한 그가 자기를 찾는 자들에게\n상 주시는 이심을 믿어야 할지니라\n\n히브리서 11:6",
  "너희가 피곤하여\n낙심하지 않기 위하여\n죄인들이 이같이\n자기에게 거역한 일을\n참으신 이를 생각하라\n\n히브리서 12:3",
  '돈을 사랑하지 말고\n있는 바를 족한 줄로 알라\n그가 친히 말씀하시기를\n내가 결코 너희를 버리지 아니하고\n너희를 떠나지 아니하리라\n하셨느니라\n\n히브리서 13:5',
  "시험을 참는 자는 복이 있나니\n이는 시련을 견디어 낸 자가\n주께서 자기를 사랑하는 자들에게\n약속하신 생명의 면류관을\n얻을 것이기 때문이라\n\n야고보서 1:12",
  "너희는\n말씀을 행하는 자가 되고\n듣기만 하여\n자신을 속이는 자가\n되지 말라\n\n야고보서 1:22",
  "누구든지\n스스로 경건하다 생각하며\n자기 혀를 재갈 물리지 아니하고\n자기 마음을 속이면\n이 사람의 경건은 헛것이라\n\n야고보서 1:26",
  "누구든지\n온 율법을 지키다가\n그 하나를 범하면\n모두 범한 자가 되나니\n\n야고보서 2:10",
  "영혼 없는 몸이\n죽은 것 같이\n행함이 없는 믿음은\n죽은 것이니라\n\n야고보서 2:26",
  "그러므로\n사람이 선을 행할 줄 알고도\n행하지 아니하면 죄니라\n\n야고보서 4:17",
  "갓난 아기들 같이\n순전하고 신령한 젖을 사모하라\n이는 그로 말미암아\n너희로 구원에 이르도록\n자라게 하려 함이라\n\n베드로전서 2:2",
  "그리스도께서도\n단번에 죄를 위하여 죽으사\n의인으로서 불의한 자를 대신하셨으니\n이는 우리를 하나님 앞으로\n인도하려 하심이라\n육체로는 죽임을 당하시고\n영으로는 살리심을 받으셨으니\n\n베드로전서 3:18",
  "만일 우리가 우리 죄를 자백하면\n그는 미쁘시고 의로우사\n우리 죄를 사하시며\n우리를 모든 불의에서\n깨끗하게 하실 것이요\n\n요한1서 1:9",
  "형제들아\n세상이 너희를 미워하여도\n이상히 여기지 말라\n\n요한1서 3:13",
  "자녀들아\n우리가 말과 혀로만\n사랑하지 말고\n행함과 진실함으로 하자\n\n요한1서 3:18",
  "여호와는\n압제를 당하는 자의 요새이시요\n환난 때의 요새이시로다\n\n시편 9:9",
  "젊은 사자는 궁핍하여 주릴지라도\n여호와를 찾는 자는\n모든 좋은 것에\n부족함이 없으리로다\n\n시편 34:10",
  "너희는\n여호와를 영원히 신뢰하라\n주 여호와는\n영원한 반석이심이로다\n\n이사야 26:4",
  "주는 나의 은신처이오니\n환난에서 나를 보호하시고\n구원의 노래로\n나를 두르시리이다\n\n시편 32:7",
  "여호와께서 이르시되\n내가 친히 가리라\n내가 너를 쉬게 하리라\n\n출애굽기 33:14",
  "그리하면 여호와 그가 네 앞에서 가시며\n너와 함께 하사 너를 떠나지 아니하시며\n버리지 아니하시리니\n너는 두려워하지 말라 놀라지 말라\n\n신명기 31:8",
  "영원하신 하나님이 네 처소가 되시니\n그의 영원하신 팔이 네 아래에 있도다\n그가 네 앞에서 대적을 쫓으시며\n멸하라 하시도다\n\n신명기 33:27",
  "의인이 부르짖으매\n여호와께서 들으시고\n그들의 모든 환난에서\n건지셨도다\n\n시편 34:17",
  "주 여호와\n이스라엘의 거룩하신 이가\n이같이 말씀하시되\n너희가 돌이켜 조용히 있어야\n구원을 얻을 것이요\n잠잠하고 신뢰하여야\n힘을 얻을 것이거늘\n너희가 원하지 아니하고\n\n이사야 30:15",
  "또 너희 중에 누가 염려함으로\n그 키를 한 자라도 더할 수 있느냐\n그런즉 가장 작은 일도 하지 못하면서\n어찌 다른 일들을 염려하느냐\n\n누가복음 12:25-26",
  "평안을 너희에게 끼치노니\n곧 나의 평안을 너희에게 주노라\n내가 너희에게 주는 것은 세상이 주는 것과 같지 아니하니라\n너희는 마음에 근심하지도 말고\n두려워하지도 말라\n\n요한복음 14:27",
  "내가 여호와께 간구하매\n내게 응답하시고\n내 모든 두려움에서\n나를 건지셨도다\n\n시편 34:4",
  "내가 네게 명령한 것이 아니냐\n강하고 담대하라\n두려워하지 말며 놀라지 말라\n네가 어디로 가든지\n네 하나님 여호와가\n너와 함께 하느니라 하시니라\n\n여호수아 1:9",
  "여호와께서는\n자기에게 간구하는 모든 자\n곧 진실하게 간구하는 모든 자에게\n가까이 하시는도다\n그는 자기를 경외하는 자들의 소원을 이루시며\n또 그들의 부르짖음을 들으사\n구원하시리로다\n\n시편 145:18-19",
  "하나님이\n우리에게 주신 것은\n두려워하는 마음이 아니요\n오직 능력과 사랑과\n절제하는 마음이니\n\n디모데후서 1:7",
  "내가 간구하는 날에\n주께서 응답하시고\n내 영혼에 힘을 주어\n나를 강하게 하셨나이다\n\n시편 138:3",
  "나의 영혼이 잠잠히 하나님만 바람이여\n나의 구원이 그에게서 나오는도다\n오직 그만이 나의 반석이시요\n나의 구원이시요 나의 요새이시니\n내가 크게 흔들리지 아니하리로다\n\n시편 62:1-2",
  "할렐루야\n여호와를 경외하며\n그의 계명을 크게 즐거워하는 자는\n복이 있도다\n\n시편 112:1",
  "나는 여호와를 향하여 말하기를\n그는 나의 피난처요\n나의 요새요\n내가 의뢰하는 하나님이라 하리니\n\n시편 91:2",
  "나에게 이르시기를 내 은혜가 네게 족하도다\n이는 내 능력이 약한 데서 온전하여짐이라 하신지라\n그러므로 도리어 크게 기뻐함으로\n나의 여러 약한 것들에 대하여 자랑하리니\n이는 그리스도의 능력이\n내게 머물게 하려 함이라\n\n고린도후서 12:9",
  "주는 미쁘사\n너희를 굳건하게 하시고\n악한 자에게서 지키시리라\n\n데살로니가후서 3:3",
  "피곤한 자에게는\n능력을 주시며\n무능한 자에게는\n힘을 더하시나니\n\n이사야 40:29",
  "모든 은혜의 하나님\n곧 그리스도 안에서 너희를 부르사\n자기의 영원한 영광에 들어가게 하신 이가\n잠깐 고난을 당한 너희를\n친히 온전하게 하시며\n굳건하게 하시며 강하게 하시며\n터를 견고하게 하시리라\n\n베드로전서 5:10",
  "평강의 주께서\n친히 때마다 일마다\n너희에게 평강을 주시고\n주께서 너희 모든 사람과\n함께 하시기를 원하노라\n\n데살로니가후서 3:16",
];

List<String> qtList = [
  "잠언 25:1~14",
  "잠언 25:1~14",
  "잠언 25:1~14",
  "잠언 25:15~28",
  "잠언 26:1~16",
  "잠언 26:17~28",
  "잠언 27:1~13",
  "잠언 27:14~27",
  "잠언 28:1~18",
  "잠언 28:19~28",
  "잠언 29:1~14",
  "잠언 29:15~27",
  "잠언 30:1~17",
  "잠언 30:18~33",
  "잠언 31:1~9",
  "잠언 31:10~31",
];

int verseNum = 0;

class VerseData {
  var rng = new Random();

  int getNum() {
    return verseNum;
  }

  String getQt(int num) {
    return qtList[num];
  }

  String getEnglish() {
    return _englishVerse[verseNum];
  }

  String getKorean() {
    return _koreanVerse[verseNum];
  }

  void renew() {
    verseNum = rng.nextInt(_englishVerse.length);
  }

  void putNum(int num) {
    verseNum = num;
  }
}
